---
version: '2.1'
services:
  kafka-ctl:
    build: ..
    environment:
      WAIT_FOR_SERVICE_UP: "tcp://kafka:9092 tcp://zookeeper:2181"
    depends_on:
      kafka:
        condition: service_started
  kafka:
    image: openshine/kafka:0.10.2.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_DELETE_TOPIC_ENABLE: "true"

    depends_on:
      zookeeper:
        condition: service_started
    healthcheck:
      test: "netstat -plnt | fgrep ':9092'"
  zookeeper:
    image: wurstmeister/zookeeper
